
2023-05-22 10:15:37 INFO: 127.0.0.1 - Signup is called
2023-05-22 10:15:37 ERROR: 127.0.0.1 - Exception on /auth/signup [POST]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/api/auth/views.py", line 47, in post
    new_user  = User (
  File "<string>", line 4, in __init__
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 1197, in _declarative_constructor
    raise TypeError(
TypeError: 'password_hash' is an invalid keyword argument for User
2023-05-22 10:16:13 INFO: 127.0.0.1 - Signup is called
2023-05-22 10:24:20 INFO: 127.0.0.1 - Signup is called
2023-05-22 10:24:20 ERROR: 127.0.0.1 - Exception on /auth/signup [POST]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/fields.py", line 464, in format
    return int(value)
ValueError: invalid literal for int() with base 10: 'e720b3c8-2f7c-40f8-a570-bf3a71c58856'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/fields.py", line 202, in output
    data = self.format(value)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/fields.py", line 466, in format
    raise MarshallingError(ve)
flask_restx.fields.MarshallingError: invalid literal for int() with base 10: 'e720b3c8-2f7c-40f8-a570-bf3a71c58856'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 252, in wrapper
    marshal(
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 54, in marshal
    out, has_wildcards = _marshal(data, fields, envelope, skip_none, mask, ordered)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 185, in _marshal
    out = OrderedDict(items) if ordered else dict(items)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 176, in <genexpr>
    else __format_field(k, v)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 170, in __format_field
    value = field.output(key, data, ordered=ordered)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/fields.py", line 207, in output
    raise MarshallingError(msg)
flask_restx.fields.MarshallingError: Unable to marshal field "id" value "e720b3c8-2f7c-40f8-a570-bf3a71c58856": invalid literal for int() with base 10: 'e720b3c8-2f7c-40f8-a570-bf3a71c58856'
2023-05-22 10:25:26 INFO: 127.0.0.1 - Signup is called
2023-05-22 10:29:40 INFO: 127.0.0.1 - Signup is called
2023-05-22 10:52:31 INFO: 127.0.0.1 - Signup is called
2023-05-22 10:52:31 ERROR: 127.0.0.1 - Exception on /auth/signup [POST]
Traceback (most recent call last):
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/venv/lib/python3.9/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/macbook/Desktop/Return/Python/Code/Scissor_RestX/api/auth/views.py", line 72, in post
    return response , HTTPStatus.CREATED
UnboundLocalError: local variable 'response' referenced before assignment
2023-05-22 10:53:44 INFO: 127.0.0.1 - Signup is called
